const types = {
  ADD_PAGE_DATA: 'METRICS/ADD_PAGE_DATA',
  ADD_ACTION_DATA: 'METRICS/ADD_ACTION_DATA',
  SAVE_PAGE_DATA_TO_DB: 'METRICS/SAVE_PAGE_DATA_TO_DB',
  SAVE_PAGE_DATA_TO_DB_SUCCESS: 'METRICS/SAVE_PAGE_DATA_TO_DB_SUCCESS',
  SAVE_PAGE_DATA_TO_DB_FAILURE: 'METRICS/SAVE_PAGE_DATA_TO_DB_FAILURE',
  SAVE_ACTION_DATA_TO_DB: 'METRICS/SAVE_ACTION_DATA_TO_DB',
  SAVE_ACTION_DATA_TO_DB_SUCCESS: 'METRICS/SAVE_ACTION_DATA_TO_DB_SUCCESS',
  SAVE_ACTION_DATA_TO_DB_FAILURE: 'METRICS/SAVE_ACTION_DATA_TO_DB_FAILURE',
};

export default types;
