const types = {
  UPDATE_QUIZ_ANSWER: 'QUIZ/UPDATE_QUIZ_ANSWER',
  CLEAR_QUIZ_ANSWERS: 'QUIZ/CLEAR_QUIZ_ANSWERS',
  POST_QUIZ_RETRIES_SUCCESS: 'QUIZ/POST_QUIZ_RETRIES_SUCCESS',
  POST_QUIZ_RETRIES_FAILURE: 'QUIZ/POST_QUIZ_RETRIES_FAILURE',
  COMPLETED_QUIZ: 'QUIZ/COMPLETED_QUIZ',
};

export default types;
